abstract class AdvertDetailsBottomSheetStates {}

class AdvertDetailsWithRoundedCornersState extends AdvertDetailsBottomSheetStates {}

class AdvertDetailsWithUsualCornersState extends AdvertDetailsBottomSheetStates {}