abstract class AdvertDetailsBottomSheetEvents {}

class AdvertDetailsWithRoundedCornersEvent extends AdvertDetailsBottomSheetEvents {}

class AdvertDetailsWithUsualCornersEvent extends AdvertDetailsBottomSheetEvents {}